const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  HeadingLevel, AlignmentType, BorderStyle, WidthType, ShadingType,
  LevelFormat, PageBreak, VerticalAlign
} = require('docx');
const fs = require('fs');

const C = {
  blue:      "1A3A5C",
  lightBlue: "2464A4",
  skyBlue:   "D0E4F4",
  midBlue:   "B8D0EB",
  darkGray:  "2B2B2B",
  midGray:   "6A6A6A",
  white:     "FFFFFF",
  yellow:    "FFFBE6",
  green:     "E8F5E2",
  orange:    "FEF0E6",
  red:       "FDE8E8",
  purple:    "F0E8FA",
};

const bd = { style: BorderStyle.SINGLE, size: 1, color: "AAAAAA" };
const bds = { top: bd, bottom: bd, left: bd, right: bd };
const thickBd = { style: BorderStyle.SINGLE, size: 5, color: C.lightBlue };
const thickBds = { top: thickBd, bottom: thickBd, left: thickBd, right: thickBd };

function h1(text) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_1,
    children: [new TextRun({ text, bold: true, color: C.white, size: 34, font: "Arial" })],
    shading: { fill: C.blue, type: ShadingType.CLEAR },
    spacing: { before: 400, after: 180 },
    indent: { left: 240 },
  });
}
function h2(text) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_2,
    children: [new TextRun({ text, bold: true, color: C.white, size: 27, font: "Arial" })],
    shading: { fill: C.lightBlue, type: ShadingType.CLEAR },
    spacing: { before: 300, after: 140 },
    indent: { left: 180 },
  });
}
function h3(text) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_3,
    children: [new TextRun({ text, bold: true, color: C.blue, size: 24, font: "Arial" })],
    border: { bottom: { style: BorderStyle.SINGLE, size: 3, color: C.lightBlue } },
    spacing: { before: 240, after: 100 },
  });
}
function h4(text) {
  return new Paragraph({
    children: [new TextRun({ text, bold: true, color: C.lightBlue, size: 22, font: "Arial" })],
    spacing: { before: 180, after: 80 },
  });
}
function para(content, opts = {}) {
  const children = typeof content === 'string'
    ? [new TextRun({ text: content, font: "Arial", size: 21, color: C.darkGray })]
    : content;
  return new Paragraph({ children, spacing: { before: 60, after: 60 }, ...opts });
}
function txt(t, extra = {}) {
  return new TextRun({ text: t, font: "Arial", size: 21, color: C.darkGray, ...extra });
}
function bold(t, color = C.blue) {
  return new TextRun({ text: t, font: "Arial", size: 21, bold: true, color });
}
function codeBlock(lines) {
  return lines.map((line, i) => new Paragraph({
    children: [new TextRun({ text: line, font: "Courier New", size: 18, color: "1E1E6A" })],
    shading: { fill: "F0F4FA", type: ShadingType.CLEAR },
    border: i === 0
      ? { top: { style: BorderStyle.SINGLE, size: 6, color: C.lightBlue }, left: { style: BorderStyle.SINGLE, size: 6, color: C.lightBlue } }
      : i === lines.length - 1
      ? { bottom: { style: BorderStyle.SINGLE, size: 6, color: C.lightBlue }, left: { style: BorderStyle.SINGLE, size: 6, color: C.lightBlue } }
      : { left: { style: BorderStyle.SINGLE, size: 6, color: C.lightBlue } },
    indent: { left: 360, right: 360 },
    spacing: { before: 28, after: 28 },
  }));
}
function noteBox(label, text, fill = C.yellow) {
  return new Table({
    width: { size: 9500, type: WidthType.DXA },
    columnWidths: [800, 8700],
    rows: [new TableRow({ children: [
      new TableCell({
        borders: bds,
        shading: { fill: C.lightBlue, type: ShadingType.CLEAR },
        width: { size: 800, type: WidthType.DXA },
        verticalAlign: VerticalAlign.CENTER,
        margins: { top: 80, bottom: 80, left: 100, right: 100 },
        children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: label, bold: true, color: C.white, font: "Arial", size: 20 })] })],
      }),
      new TableCell({
        borders: bds,
        shading: { fill, type: ShadingType.CLEAR },
        width: { size: 8700, type: WidthType.DXA },
        margins: { top: 80, bottom: 80, left: 160, right: 120 },
        children: [para(text)],
      }),
    ]})],
  });
}
function hRow(cells, widths, fill = C.midBlue) {
  return new TableRow({
    tableHeader: true,
    children: cells.map((c, i) => new TableCell({
      borders: bds,
      shading: { fill, type: ShadingType.CLEAR },
      width: { size: widths[i], type: WidthType.DXA },
      margins: { top: 80, bottom: 80, left: 110, right: 110 },
      children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: c, bold: true, font: "Arial", size: 20, color: C.blue })] })],
    }))
  });
}
function dRow(cells, widths, shade = C.white) {
  return new TableRow({
    children: cells.map((c, i) => new TableCell({
      borders: bds,
      shading: { fill: shade, type: ShadingType.CLEAR },
      width: { size: widths[i], type: WidthType.DXA },
      margins: { top: 60, bottom: 60, left: 110, right: 110 },
      children: [new Paragraph({ children: [new TextRun({ text: c, font: "Arial", size: 19, color: C.darkGray })] })],
    }))
  });
}
function sp(n = 1) { return Array(n).fill(new Paragraph({ children: [txt("")], spacing: { before: 40, after: 40 } })); }
function div() {
  return new Paragraph({
    children: [txt("")],
    border: { bottom: { style: BorderStyle.SINGLE, size: 3, color: C.lightBlue } },
    spacing: { before: 120, after: 120 },
  });
}
function bullet(content) {
  const children = typeof content === 'string' ? [txt(content)] : content;
  return new Paragraph({ numbering: { reference: "bullets", level: 0 }, children, spacing: { before: 60, after: 60 } });
}
function num(content) {
  const children = typeof content === 'string' ? [txt(content)] : content;
  return new Paragraph({ numbering: { reference: "numbers", level: 0 }, children, spacing: { before: 60, after: 60 } });
}

// ─── Main Document ────────────────────────────────────────────────
const doc = new Document({
  styles: {
    default: { document: { run: { font: "Arial", size: 21 } } },
    paragraphStyles: [
      { id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 34, bold: true, font: "Arial" }, paragraph: { spacing: { before: 400, after: 180 }, outlineLevel: 0 } },
      { id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 27, bold: true, font: "Arial" }, paragraph: { spacing: { before: 300, after: 140 }, outlineLevel: 1 } },
      { id: "Heading3", name: "Heading 3", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 24, bold: true, font: "Arial" }, paragraph: { spacing: { before: 240, after: 100 }, outlineLevel: 2 } },
    ]
  },
  numbering: {
    config: [
      { reference: "bullets", levels: [{ level: 0, format: LevelFormat.BULLET, text: "\u2022",
          alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 720, hanging: 360 } } } }] },
      { reference: "numbers", levels: [{ level: 0, format: LevelFormat.DECIMAL, text: "%1.",
          alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 720, hanging: 360 } } } }] },
      { reference: "numbers2", levels: [{ level: 0, format: LevelFormat.DECIMAL, text: "%1.",
          alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 720, hanging: 360 } } } }] },
    ]
  },
  sections: [{
    properties: {
      page: { size: { width: 11906, height: 16838 }, margin: { top: 1000, right: 1000, bottom: 1000, left: 1000 } }
    },
    children: [

      // ═══════════════════ 封面 ═══════════════════
      ...sp(2),
      new Paragraph({
        alignment: AlignmentType.CENTER,
        shading: { fill: C.blue, type: ShadingType.CLEAR },
        spacing: { before: 0, after: 0 },
        children: [new TextRun({ text: "线路距离保护校验", bold: true, size: 60, font: "Arial", color: C.white, break: 1 })],
      }),
      new Paragraph({
        alignment: AlignmentType.CENTER,
        shading: { fill: C.lightBlue, type: ShadingType.CLEAR },
        spacing: { before: 0, after: 0 },
        children: [new TextRun({ text: "核心算法与继保测试仪接线指导手册", size: 34, font: "Arial", color: C.white, break: 1 })],
      }),
      new Paragraph({
        alignment: AlignmentType.CENTER,
        shading: { fill: C.skyBlue, type: ShadingType.CLEAR },
        spacing: { before: 0, after: 0 },
        children: [new TextRun({ text: "适用范围：相间距离 / 接地距离 | I/II/III 段 | 圆特性 / 多边形特性 | 定电压算电流 / 定电流算电压", size: 21, font: "Arial", color: C.blue })],
      }),
      ...sp(2),
      new Table({
        width: { size: 9500, type: WidthType.DXA },
        columnWidths: [9500],
        rows: [new TableRow({ children: [new TableCell({
          borders: thickBds,
          shading: { fill: C.skyBlue, type: ShadingType.CLEAR },
          margins: { top: 200, bottom: 200, left: 300, right: 300 },
          children: [
            new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: "本文档供 AI 编程助手阅读学习，包含：", bold: true, font: "Arial", size: 24, color: C.blue })] }),
            bullet("距离保护基本原理与测量阻抗计算方法（相间 / 接地 / 三相）"),
            bullet("两种计算模式：定电压求电流、定电流求电压，含完整 Python 伪代码"),
            bullet("I / II / III 段阻抗整定值与动作时间的判断逻辑"),
            bullet("保护方向边界校验：正向灵敏角、反向死区、精确边界扫描算法"),
            bullet("继保测试仪接线方案：三路电压三路电流的标准接法与注意事项"),
            bullet("单相、两相、三相各种故障模式下的电流电压相量计算"),
          ]
        })] })] }),
      new Paragraph({ children: [new PageBreak()] }),

      // ═══════════════════ 第一章 ═══════════════════
      h1("第一章  距离保护基本原理"),

      h2("1.1  距离保护测量原理"),
      para("距离保护通过测量保护安装处到故障点的阻抗来判断故障位置。当测量阻抗落入整定阻抗圆（或多边形）内时，保护动作。"),
      ...sp(1),
      ...codeBlock([
        "  保护安装处的测量阻抗（相间故障以 AB 为例）：",
        "",
        "    Z_measure = U_AB / I_AB",
        "",
        "  其中：",
        "    U_AB  = 保护安装处 A、B 两相线电压（向量差）",
        "    I_AB  = 故障回路电流 = I_A - I_B",
        "",
        "  接地故障（以 A 相接地为例）：",
        "    Z_measure = U_A / (I_A + K0 × 3I0)",
        "",
        "  其中：",
        "    K0 = (Z0 - Z1) / (3 × Z1)    零序补偿系数",
        "    3I0 = I_A + I_B + I_C         零序电流",
      ]),
      ...sp(1),

      h2("1.2  阻抗特性类型"),
      new Table({
        width: { size: 9500, type: WidthType.DXA },
        columnWidths: [2000, 2800, 4700],
        rows: [
          hRow(["特性类型", "动作判据", "优缺点与适用场合"], [2000, 2800, 4700]),
          dRow(["圆特性（Mho）", "|Z - Zset/2| ≤ |Zset/2|", "方向性自带，受弧光电阻影响大，中性点直接接地系统常用"], [2000, 2800, 4700]),
          dRow(["偏移圆特性", "|Z - Zoffset| ≤ R_circle", "可兼顾反向一定范围，解决出口故障死区问题"], [2000, 2800, 4700], C.skyBlue),
          dRow(["多边形特性（Quadrilateral）", "R分量 < Rset 且 X分量 < Xset", "耐弧光电阻能力强，高阻接地场合优选"], [2000, 2800, 4700]),
          dRow(["透镜特性", "椭圆边界判据", "对有载调压变压器系统较好，较少见"], [2000, 2800, 4700], C.skyBlue),
        ]
      }),
      ...sp(1),

      h2("1.3  段别与时间"),
      ...codeBlock([
        "  整定逻辑（以正向三段式为例）：",
        "",
        "    if Z_measure 在 I 段范围内:",
        "        动作时间 t = t_I   （通常 0s，瞬动）",
        "    elif Z_measure 在 II 段范围内:",
        "        动作时间 t = t_II  （如 0.5s）",
        "    elif Z_measure 在 III 段范围内:",
        "        动作时间 t = t_III （如 1.5s）",
        "    else:",
        "        不动作",
        "",
        "  Mho 圆特性段别判断（以复平面为基础）：",
        "    段 n 动作条件：|Z_m - Z_n/2| <= |Z_n/2|",
        "    等价于：Re(U_AB × conj(I_AB × Z_n - U_AB)) >= 0",
      ]),
      ...sp(2),
      new Paragraph({ children: [new PageBreak()] }),

      // ═══════════════════ 第二章 ═══════════════════
      h1("第二章  系统参数与输入定义"),

      h2("2.1  系统参数"),
      new Table({
        width: { size: 9500, type: WidthType.DXA },
        columnWidths: [2200, 1300, 1400, 4600],
        rows: [
          hRow(["参数", "符号", "示例值", "说明"], [2200, 1300, 1400, 4600]),
          dRow(["系统额定电压（线电压）", "Un_kV", "110 kV", "变电站母线额定线电压"], [2200, 1300, 1400, 4600]),
          dRow(["CT 变比", "nCT", "600/5", "保护用CT，如写60.0"], [2200, 1300, 1400, 4600], C.skyBlue),
          dRow(["PT 变比", "nPT", "110000/100", "保护用PT，如写1100.0"], [2200, 1300, 1400, 4600]),
          dRow(["线路正序阻抗（单位长度）", "Z1_per_km", "0.4+j0.4 Ω/km", "一次侧，复数"], [2200, 1300, 1400, 4600], C.skyBlue),
          dRow(["线路零序阻抗（单位长度）", "Z0_per_km", "0.8+j1.2 Ω/km", "一次侧，复数"], [2200, 1300, 1400, 4600]),
          dRow(["线路全长", "L_km", "80 km", "保护线路总长度"], [2200, 1300, 1400, 4600], C.skyBlue),
          dRow(["等效系统阻抗", "Zs", "2+j8 Ω", "背后系统正序阻抗，一次侧"], [2200, 1300, 1400, 4600]),
          dRow(["过渡电阻", "Rf_ohm", "0 ~ 30 Ω", "故障弧光电阻，一次侧，通常0"], [2200, 1300, 1400, 4600], C.skyBlue),
        ]
      }),
      ...sp(1),

      h2("2.2  保护整定参数"),
      new Table({
        width: { size: 9500, type: WidthType.DXA },
        columnWidths: [2200, 1600, 1400, 4300],
        rows: [
          hRow(["参数", "符号", "示例值（二次侧Ω）", "说明"], [2200, 1600, 1400, 4300]),
          dRow(["I 段阻抗整定值", "Zset_I", "10.5+j18.2", "二次侧复数，通常 80% 全长正序阻抗"], [2200, 1600, 1400, 4300]),
          dRow(["II 段阻抗整定值", "Zset_II", "15.8+j27.3", "二次侧，含对侧变压器阻抗"], [2200, 1600, 1400, 4300], C.skyBlue),
          dRow(["III 段阻抗整定值", "Zset_III", "25.0+j43.3", "二次侧，含远端系统阻抗"], [2200, 1600, 1400, 4300]),
          dRow(["I 段动作时间", "t_I", "0 s", "瞬动"], [2200, 1600, 1400, 4300], C.skyBlue),
          dRow(["II 段动作时间", "t_II", "0.5 s", ""], [2200, 1600, 1400, 4300]),
          dRow(["III 段动作时间", "t_III", "1.5 s", ""], [2200, 1600, 1400, 4300], C.skyBlue),
          dRow(["阻抗角（线路灵敏角）", "phi_set_deg", "70°", "整定阻抗的幅角，即线路阻抗角"], [2200, 1600, 1400, 4300]),
          dRow(["最大灵敏角", "phi_max_deg", "70°", "部分装置可独立设置，通常等于 phi_set"], [2200, 1600, 1400, 4300], C.skyBlue),
          dRow(["阻抗特性类型", "char_type", "'mho' / 'quad'", "圆特性或四边形特性"], [2200, 1600, 1400, 4300]),
          dRow(["零序补偿系数", "K0", "复数", "由 Z0/Z1 计算，见第三章"], [2200, 1600, 1400, 4300], C.skyBlue),
        ]
      }),
      ...sp(1),

      h2("2.3  测试工况参数"),
      new Table({
        width: { size: 9500, type: WidthType.DXA },
        columnWidths: [2400, 2000, 5100],
        rows: [
          hRow(["参数", "取值范围", "说明"], [2400, 2000, 5100]),
          dRow(["故障类型 fault_type", "AB/BC/CA/AG/BG/CG/ABG/BCG/CAG/ABC", "决定测量回路和注入相位"], [2400, 2000, 5100]),
          dRow(["计算模式 calc_mode", "'fixed_U' / 'fixed_I'", "定电压求电流，或定电流求电压"], [2400, 2000, 5100], C.skyBlue),
          dRow(["固定量幅值", "U_fixed / I_fixed", "定电压模式输入电压(V二次)，定电流模式输入电流(A二次)"], [2400, 2000, 5100]),
          dRow(["目标测量阻抗", "Zm_target", "复数(Ω二次)，落在某段范围内的期望阻抗值"], [2400, 2000, 5100], C.skyBlue),
          dRow(["测试目的 test_purpose", "'operate'/'boundary'/'no_op'", "期望动作 / 边界 / 不动作"], [2400, 2000, 5100]),
          dRow(["段别 zone", "1 / 2 / 3", "校验哪一段的整定值"], [2400, 2000, 5100], C.skyBlue),
        ]
      }),
      ...sp(2),
      new Paragraph({ children: [new PageBreak()] }),

      // ═══════════════════ 第三章 ═══════════════════
      h1("第三章  故障电气量计算算法"),

      h2("3.1  基础变换与零序补偿系数"),
      ...codeBlock([
        "import cmath, math",
        "import numpy as np",
        "",
        "def calc_K0(Z1_per_km, Z0_per_km):",
        "    \"\"\"零序补偿系数 K0 = (Z0 - Z1) / (3 * Z1)\"\"\"",
        "    Z1 = complex(Z1_per_km[0], Z1_per_km[1])",
        "    Z0 = complex(Z0_per_km[0], Z0_per_km[1])",
        "    return (Z0 - Z1) / (3 * Z1)",
        "",
        "def convert_to_secondary(Z_primary, nCT, nPT):",
        "    \"\"\"一次阻抗折算到二次侧\"\"\"",
        "    return Z_primary * nCT / nPT",
        "",
        "def angle_deg(z):",
        "    return math.degrees(cmath.phase(z))",
      ]),
      ...sp(1),

      h2("3.2  相间短路（重点）"),
      para([bold("相间短路是距离保护校验最主要的场景"), txt("，以 AB 相间短路为例，其他相间故障旋转对称处理。")]),
      ...sp(1),

      h3("3.2.1  故障分析（一次侧计算）"),
      ...codeBlock([
        "def calc_phase_fault_primary(Un_kV, Zs, Z1_per_km, d_km, Rf, fault_type):",
        "    \"\"\"",
        "    计算保护安装处一次侧电气量",
        "    fault_type: 'AB' / 'BC' / 'CA'",
        "    \"\"\"",
        "    pi = math.pi",
        "    j  = 1j",
        "",
        "    E_ph = (Un_kV * 1000) / math.sqrt(3)   # 相电压有效值",
        "",
        "    # 故障点阻抗（一次，含过渡电阻）",
        "    Z1_line = complex(Z1_per_km[0], Z1_per_km[1]) * d_km",
        "    Z_fault = Z1_line + Rf   # 过渡电阻只有实部",
        "",
        "    # 相间短路等效：两相回路阻抗 = 2 × (系统阻抗 + 故障点阻抗)",
        "    # 参考相角偏移（让所选相对在标准位置）",
        "    angle_map = {'AB': 0.0, 'BC': -2*pi/3, 'CA': 2*pi/3}",
        "    theta = angle_map[fault_type]",
        "",
        "    E_x = E_ph * cmath.exp(1j * (theta + pi/6))      # 故障相线电压幅值对应的相电势",
        "    E_y = E_ph * cmath.exp(1j * (theta + pi/6 - 2*pi/3))",
        "",
        "    Zs_c = complex(Zs[0], Zs[1])",
        "    Z_total = Zs_c + Z_fault",
        "",
        "    # 故障电流（相间回路）",
        "    I_x = (E_x - E_y) / (2 * Z_total)",
        "    I_y = -I_x",
        "",
        "    # 保护处各相电压",
        "    U_x = E_x - I_x * Zs_c",
        "    U_y = E_y - I_y * Zs_c",
        "    U_xy = U_x - U_y   # 线电压（故障相间）",
        "",
        "    # 非故障相（正常相电压近似保持额定）",
        "    theta_3rd = theta + 2*pi/3 + pi/6",
        "    U_z = E_ph * cmath.exp(1j * theta_3rd)   # 近似：无穿越电流",
        "",
        "    return {",
        "        'I_fault_x': I_x,   # 故障相1电流（复数，一次A）",
        "        'I_fault_y': I_y,   # 故障相2电流",
        "        'I_nonfault': 0+0j, # 非故障相电流（近似）",
        "        'U_fault_xy': U_xy, # 故障相间线电压",
        "        'U_x': U_x,         # 故障相1电压",
        "        'U_y': U_y,         # 故障相2电压",
        "        'U_z': U_z,         # 非故障相电压",
        "        'Z_measure_1st': U_xy / (I_x - I_y),  # 测量阻抗一次侧",
        "    }",
      ]),
      ...sp(1),

      h3("3.2.2  折算到二次侧"),
      ...codeBlock([
        "def to_secondary(primary_result, nCT, nPT):",
        "    \"\"\"将一次侧计算结果折算到二次侧（测试仪实际输出值）\"\"\"",
        "    r = primary_result",
        "    return {",
        "        # 电流二次值（直接注入测试仪电流端）",
        "        'I_x_2nd':  r['I_fault_x'] / nCT,",
        "        'I_y_2nd':  r['I_fault_y'] / nCT,",
        "        'I_z_2nd':  r['I_nonfault'] / nCT,",
        "        # 电压二次值（注入测试仪电压端）",
        "        'U_xy_2nd': r['U_fault_xy'] / nPT,",
        "        'U_x_2nd':  r['U_x'] / nPT,",
        "        'U_y_2nd':  r['U_y'] / nPT,",
        "        'U_z_2nd':  r['U_z'] / nPT,",
        "        # 测量阻抗二次值",
        "        'Zm_2nd':   r['Z_measure_1st'] * nCT / nPT,",
        "    }",
      ]),
      ...sp(1),

      h2("3.3  两种计算模式"),
      noteBox("模式说明", "实际调试中根据继保仪能力选择：定电压（固定UN/√3）算电流，适合电压源型仪器；定电流（固定5A或1A）算电压，适合电流源型仪器。两种模式在目标测量阻抗相同时结果等价。", C.yellow),
      ...sp(1),

      h3("3.3.1  模式一：定电压求电流（fixed_U）"),
      ...codeBlock([
        "def calc_fixed_voltage(Zm_target_2nd, U_fixed_2nd, fault_type, phi_set_deg):",
        "    \"\"\"",
        "    给定：目标测量阻抗 Zm（二次，复数）、固定电压幅值 U（二次，V）",
        "    求：  需要注入的电流（二次，A）",
        "",
        "    测量阻抗定义：Zm = U_fault / I_fault_loop",
        "    →  I_fault_loop = U_fault / Zm",
        "",
        "    U_fault 方向：取线电压方向，幅值由 U_fixed 给定",
        "    U 相角参考：令 U_AB 超前 0°，即 U_AB 为实数",
        "    \"\"\"",
        "    pi = math.pi",
        "",
        "    # 故障回路线电压（参考相量）",
        "    U_fault_2nd = complex(U_fixed_2nd, 0)   # U_AB 取为实轴参考",
        "",
        "    # 故障回路电流",
        "    I_loop_2nd = U_fault_2nd / Zm_target_2nd",
        "",
        "    # 故障类型决定各相的相量关系",
        "    angle_map = {'AB': 0.0, 'BC': -2*pi/3, 'CA': 2*pi/3,",
        "                 'AG': 0.0, 'BG': -2*pi/3, 'CG': 2*pi/3,",
        "                 'ABC': 0.0}",
        "    base_angle = angle_map.get(fault_type, 0.0)",
        "",
        "    # 各相电流（以 AB 相间为标准，旋转到对应故障相）",
        "    I_A = I_loop_2nd * cmath.exp(1j * base_angle)       if 'A' in fault_type else 0+0j",
        "    I_B = -I_loop_2nd * cmath.exp(1j * base_angle)      if 'B' in fault_type else 0+0j",
        "    I_C = 0+0j  # 相间故障第三相无电流（近似）",
        "",
        "    # 各相电压（从 U_fault 反推相电压）",
        "    U_A_ref = U_fixed_2nd * cmath.exp(1j * (base_angle + pi/6)) / math.sqrt(3)",
        "    U_B_ref = U_A_ref * cmath.exp(-1j * 2*pi/3)",
        "    U_C_ref = U_A_ref * cmath.exp(1j * 2*pi/3)",
        "",
        "    return {",
        "        'mode': 'fixed_U',",
        "        'U_fixed_V': U_fixed_2nd,",
        "        'I_loop_A':  abs(I_loop_2nd),",
        "        'I_loop_ang': angle_deg(I_loop_2nd),",
        "        'Zm_check':  U_fault_2nd / I_loop_2nd,  # 应等于 Zm_target",
        "        # 注入量",
        "        'inject_I': {",
        "            'I_A': {'mag': abs(I_A), 'ang': angle_deg(I_A)},",
        "            'I_B': {'mag': abs(I_B), 'ang': angle_deg(I_B)},",
        "            'I_C': {'mag': abs(I_C), 'ang': angle_deg(I_C)},",
        "        },",
        "        'inject_U': {",
        "            'U_A': {'mag': abs(U_A_ref), 'ang': angle_deg(U_A_ref)},",
        "            'U_B': {'mag': abs(U_B_ref), 'ang': angle_deg(U_B_ref)},",
        "            'U_C': {'mag': abs(U_C_ref), 'ang': angle_deg(U_C_ref)},",
        "        }",
        "    }",
      ]),
      ...sp(1),

      h3("3.3.2  模式二：定电流求电压（fixed_I）"),
      ...codeBlock([
        "def calc_fixed_current(Zm_target_2nd, I_fixed_2nd, fault_type):",
        "    \"\"\"",
        "    给定：目标测量阻抗 Zm（二次，复数）、固定电流幅值 I（二次，A）",
        "    求：  需要加的电压（二次，V）",
        "",
        "    测量阻抗定义：Zm = U_fault / I_fault_loop",
        "    →  U_fault = I_fault_loop × Zm",
        "    \"\"\"",
        "    pi = math.pi",
        "",
        "    angle_map = {'AB': 0.0, 'BC': -2*pi/3, 'CA': 2*pi/3,",
        "                 'AG': 0.0, 'BG': -2*pi/3, 'CG': 2*pi/3, 'ABC': 0.0}",
        "    base_angle = angle_map.get(fault_type, 0.0)",
        "",
        "    # 故障回路电流（固定幅值，取参考方向）",
        "    I_loop_2nd = I_fixed_2nd * cmath.exp(1j * base_angle)",
        "",
        "    # 故障线电压",
        "    U_fault_2nd = I_loop_2nd * Zm_target_2nd",
        "",
        "    # 各相电压反推",
        "    U_A_ref = U_fault_2nd / math.sqrt(3) * cmath.exp(1j * pi/6)",
        "    U_B_ref = U_A_ref * cmath.exp(-1j * 2*pi/3)",
        "    U_C_ref = U_A_ref * cmath.exp(1j * 2*pi/3)",
        "",
        "    # 各相电流",
        "    I_A = I_loop_2nd if 'A' in fault_type and fault_type != 'ABC' else (",
        "          I_fixed_2nd * cmath.exp(1j * base_angle) if fault_type == 'ABC' else 0+0j)",
        "    I_B = -I_loop_2nd if fault_type in ['AB','BC','CA'] and 'B' in fault_type else (",
        "          I_fixed_2nd * cmath.exp(1j * (base_angle - 2*pi/3)) if fault_type == 'ABC' else 0+0j)",
        "    I_C = I_fixed_2nd * cmath.exp(1j * (base_angle + 2*pi/3)) if fault_type == 'ABC' else 0+0j",
        "",
        "    return {",
        "        'mode': 'fixed_I',",
        "        'I_fixed_A': I_fixed_2nd,",
        "        'U_fault_V': abs(U_fault_2nd),",
        "        'U_fault_ang': angle_deg(U_fault_2nd),",
        "        'Zm_check': U_fault_2nd / I_loop_2nd,",
        "        'inject_I': {",
        "            'I_A': {'mag': abs(I_A), 'ang': angle_deg(I_A)},",
        "            'I_B': {'mag': abs(I_B), 'ang': angle_deg(I_B)},",
        "            'I_C': {'mag': abs(I_C), 'ang': angle_deg(I_C)},",
        "        },",
        "        'inject_U': {",
        "            'U_A': {'mag': abs(U_A_ref), 'ang': angle_deg(U_A_ref)},",
        "            'U_B': {'mag': abs(U_B_ref), 'ang': angle_deg(U_B_ref)},",
        "            'U_C': {'mag': abs(U_C_ref), 'ang': angle_deg(U_C_ref)},",
        "        }",
        "    }",
      ]),
      ...sp(2),
      new Paragraph({ children: [new PageBreak()] }),

      // ═══════════════════ 第四章 ═══════════════════
      h1("第四章  各类故障模式计算"),

      h2("4.1  故障类型与测量回路对照"),
      new Table({
        width: { size: 9500, type: WidthType.DXA },
        columnWidths: [1400, 1800, 1800, 1800, 2700],
        rows: [
          hRow(["故障类型", "测量电压", "测量电流", "零序补偿", "备注"], [1400, 1800, 1800, 1800, 2700]),
          dRow(["AB 相间", "U_A - U_B", "I_A - I_B", "无", "相间故障无零序分量"], [1400, 1800, 1800, 1800, 2700]),
          dRow(["BC 相间", "U_B - U_C", "I_B - I_C", "无", "旋转 120°"], [1400, 1800, 1800, 1800, 2700], C.skyBlue),
          dRow(["CA 相间", "U_C - U_A", "I_C - I_A", "无", "旋转 240°"], [1400, 1800, 1800, 1800, 2700]),
          dRow(["A 相接地", "U_A", "I_A + K0·3I0", "有", "需准确计算K0"], [1400, 1800, 1800, 1800, 2700], C.skyBlue),
          dRow(["B 相接地", "U_B", "I_B + K0·3I0", "有", ""], [1400, 1800, 1800, 1800, 2700]),
          dRow(["C 相接地", "U_C", "I_C + K0·3I0", "有", ""], [1400, 1800, 1800, 1800, 2700], C.skyBlue),
          dRow(["两相接地 ABG", "U_A - U_B", "I_A - I_B（相间距离）", "特殊", "按相间处理，另设接地保护"], [1400, 1800, 1800, 1800, 2700]),
          dRow(["三相短路 ABC", "U_A - U_B", "I_A - I_B", "无", "对称故障，各相幅值相等"], [1400, 1800, 1800, 1800, 2700], C.skyBlue),
        ]
      }),
      ...sp(1),

      h2("4.2  接地故障计算（含零序补偿）"),
      ...codeBlock([
        "def calc_ground_fault(Un_kV, Zs, Z1_per_km, Z0_per_km, d_km, Rf, fault_type):",
        "    \"\"\"",
        "    接地故障（单相接地 AG/BG/CG）",
        "    fault_type: 'AG' / 'BG' / 'CG'",
        "    \"\"\"",
        "    pi = math.pi",
        "    j  = 1j",
        "",
        "    E_ph = (Un_kV * 1000) / math.sqrt(3)",
        "    Z1 = complex(Z1_per_km[0], Z1_per_km[1])",
        "    Z0 = complex(Z0_per_km[0], Z0_per_km[1])",
        "    K0 = (Z0 - Z1) / (3 * Z1)",
        "",
        "    # 故障相参考角",
        "    angle_map = {'AG': 0.0, 'BG': -2*pi/3, 'CG': 2*pi/3}",
        "    theta = angle_map[fault_type]",
        "",
        "    Z1_fault = Z1 * d_km + Rf",
        "    Z0_fault = Z0 * d_km + Rf",
        "    Zs_1 = complex(Zs[0], Zs[1])",
        "    Zs_0 = Zs_1 * 3   # 近似：零序系统阻抗",
        "",
        "    # 对称分量法求故障电流",
        "    # 单相接地：I1 = I2 = I0 = E / (Z1_total + Z2_total + Z0_total)",
        "    Z1_total = Zs_1 + Z1_fault",
        "    Z2_total = Z1_total   # 正序=负序（无旋转机）",
        "    Z0_total = Zs_0 + Z0_fault",
        "    I0 = E_ph * cmath.exp(1j * theta) / (Z1_total + Z2_total + Z0_total)",
        "    I1 = I0",
        "    I2 = I0",
        "",
        "    a  = cmath.exp(1j * 2*pi/3)",
        "    a2 = a * a",
        "",
        "    # 各相电流（序分量合成，对 A 相接地）",
        "    I_A = I0 + I1 + I2",
        "    I_B = I0 + a2*I1 + a*I2",
        "    I_C = I0 + a*I1 + a2*I2",
        "",
        "    # 零序电流",
        "    I_3I0 = 3 * I0",
        "",
        "    # 保护处各相电压",
        "    U1 = E_ph*cmath.exp(1j*theta) - I1 * Zs_1",
        "    U2 = -I2 * Zs_1",
        "    U0 = -I0 * Zs_0",
        "    U_A = U0 + U1 + U2",
        "    U_B = U0 + a2*U1 + a*U2",
        "    U_C = U0 + a*U1 + a2*U2",
        "",
        "    # 测量阻抗（接地距离）",
        "    I_measure = I_A + K0 * I_3I0   # 零序补偿后的测量电流",
        "    Z_measure = U_A / I_measure",
        "",
        "    return {",
        "        'fault_type': fault_type,",
        "        'K0': K0,",
        "        'I_A': I_A, 'I_B': I_B, 'I_C': I_C, 'I_3I0': I_3I0,",
        "        'U_A': U_A, 'U_B': U_B, 'U_C': U_C,",
        "        'I_measure': I_measure,",
        "        'Z_measure_1st': Z_measure,",
        "    }",
      ]),
      ...sp(1),

      h2("4.3  三相短路计算"),
      ...codeBlock([
        "def calc_three_phase_fault(Un_kV, Zs, Z1_per_km, d_km, Rf):",
        "    \"\"\"",
        "    三相对称短路：I0=I2=0，只有正序分量",
        "    测量回路与相间故障相同（取 AB 回路）",
        "    \"\"\"",
        "    pi = math.pi",
        "",
        "    E_ph  = (Un_kV * 1000) / math.sqrt(3)",
        "    Z1    = complex(Z1_per_km[0], Z1_per_km[1])",
        "    Z1_f  = Z1 * d_km + Rf",
        "    Zs_c  = complex(Zs[0], Zs[1])",
        "    Z_tot = Zs_c + Z1_f",
        "",
        "    a  = cmath.exp(1j * 2*pi/3)",
        "    a2 = a * a",
        "",
        "    I1 = E_ph / Z_tot",
        "    I_A = I1",
        "    I_B = a2 * I1",
        "    I_C = a  * I1",
        "",
        "    U_A = E_ph - I_A * Zs_c",
        "    U_B = a2 * E_ph - I_B * Zs_c",
        "    U_C = a  * E_ph - I_C * Zs_c",
        "",
        "    Z_measure = (U_A - U_B) / (I_A - I_B)   # 等于 Z1_f（无零序）",
        "",
        "    return {",
        "        'I_A': I_A, 'I_B': I_B, 'I_C': I_C,",
        "        'U_A': U_A, 'U_B': U_B, 'U_C': U_C,",
        "        'Z_measure_1st': Z_measure,",
        "    }",
      ]),
      ...sp(2),
      new Paragraph({ children: [new PageBreak()] }),

      // ═══════════════════ 第五章 ═══════════════════
      h1("第五章  阻抗特性判断与方向边界校验"),

      h2("5.1  Mho 圆特性判断"),
      ...codeBlock([
        "def is_in_mho(Zm, Zset):",
        "    \"\"\"",
        "    判断测量阻抗 Zm 是否在以 Zset 为直径的 Mho 圆内",
        "    动作条件：|Zm - Zset/2| <= |Zset/2|",
        "    等价（向量积形式）：Re(Zm × conj(Zset)) >= |Zm|²",
        "    \"\"\"",
        "    center = Zset / 2",
        "    radius = abs(Zset) / 2",
        "    return abs(Zm - center) <= radius",
        "",
        "def mho_margin(Zm, Zset):",
        "    \"\"\"返回距动作边界的裕度（正=圆内动作，负=圆外不动）\"\"\"",
        "    center = Zset / 2",
        "    radius = abs(Zset) / 2",
        "    return radius - abs(Zm - center)",
      ]),
      ...sp(1),

      h2("5.2  四边形特性判断"),
      ...codeBlock([
        "def is_in_quadrilateral(Zm, Rset, Xset, phi_set_deg):",
        "    \"\"\"",
        "    四边形（多边形）特性判断",
        "    动作条件：",
        "      1. 电阻分量（沿灵敏角方向投影）< Rset",
        "      2. 电抗分量（垂直灵敏角方向）< Xset",
        "      3. 满足方向性（Zm 在灵敏角 ± 90° 范围内）",
        "    \"\"\"",
        "    phi = math.radians(phi_set_deg)",
        "    # 旋转坐标系到灵敏角方向",
        "    Zm_rot = Zm * cmath.exp(-1j * phi)",
        "    R_proj = Zm_rot.real",
        "    X_proj = Zm_rot.imag",
        "    in_R   = 0 < R_proj < Rset",
        "    in_X   = 0 < X_proj < Xset",
        "    return in_R and in_X",
      ]),
      ...sp(1),

      h2("5.3  段别判断主函数"),
      ...codeBlock([
        "def judge_zone(Zm_2nd, Zset_I, Zset_II, Zset_III, char_type='mho',",
        "               t_I=0.0, t_II=0.5, t_III=1.5):",
        "    \"\"\"",
        "    返回测量阻抗 Zm 对应的保护段别和动作时间",
        "    Zset_* 均为二次侧复数阻抗",
        "    \"\"\"",
        "    def check(Zset):",
        "        if char_type == 'mho':",
        "            return is_in_mho(Zm_2nd, Zset)",
        "        else:  # quad",
        "            return is_in_quadrilateral(Zm_2nd,",
        "                       Rset=abs(Zset)*math.cos(cmath.phase(Zset)),",
        "                       Xset=abs(Zset)*math.sin(cmath.phase(Zset)),",
        "                       phi_set_deg=math.degrees(cmath.phase(Zset)))",
        "",
        "    if check(Zset_I):",
        "        return {'zone': 1, 't_action': t_I,   'in_zone': True}",
        "    elif check(Zset_II):",
        "        return {'zone': 2, 't_action': t_II,  'in_zone': True}",
        "    elif check(Zset_III):",
        "        return {'zone': 3, 't_action': t_III, 'in_zone': True}",
        "    else:",
        "        return {'zone': None, 't_action': None, 'in_zone': False}",
      ]),
      ...sp(1),

      h2("5.4  保护方向边界校验"),
      para([bold("方向边界"), txt("是距离保护校验的关键项目，包括：正向灵敏角边界（电流超前电压多少度时动作最灵敏）、正反向边界（何时从动作变为不动作）、反向死区。")]),
      ...sp(1),

      h3("5.4.1  灵敏角（最大灵敏角方向）"),
      ...codeBlock([
        "def calc_max_sensitivity_angle(Zset, char_type='mho'):",
        "    \"\"\"",
        "    Mho 圆特性：最大灵敏角 = Zset 的幅角",
        "    即电压超前电流角度 = phi_set 时，保护最灵敏",
        "    （允许最大阻抗距离）",
        "    \"\"\"",
        "    phi_max = math.degrees(cmath.phase(Zset))",
        "    return phi_max   # 度，正值表示容性方向",
        "",
        "",
        "def calc_direction_boundary_inject(Zset_2nd, I_fixed, phi_target_deg,",
        "                                   fault_type='AB', mode='fixed_I'):",
        "    \"\"\"",
        "    给定期望的电压超前电流角度（phi），计算注入量，",
        "    用于扫描方向边界",
        "",
        "    phi_target_deg > 0：电压超前电流（感性负载方向，正常正向）",
        "    phi_target_deg < 0：电压滞后电流（反向故障方向）",
        "    \"\"\"",
        "    phi_rad = math.radians(phi_target_deg)",
        "",
        "    # 固定电流方向为参考（0°），电压按 phi 角超前",
        "    I_ref  = complex(I_fixed, 0)",
        "    U_ref  = abs(Zset_2nd) * I_fixed * cmath.exp(1j * phi_rad)",
        "",
        "    # 此时测量阻抗",
        "    Zm = U_ref / I_ref",
        "",
        "    return {",
        "        'phi_deg':   phi_target_deg,",
        "        'Zm':        Zm,",
        "        'in_zone':   is_in_mho(Zm, Zset_2nd),",
        "        'I_A_mag':   I_fixed,",
        "        'I_A_ang':   0.0,",
        "        'U_fault_mag': abs(U_ref),",
        "        'U_fault_ang': math.degrees(cmath.phase(U_ref)),",
        "    }",
      ]),
      ...sp(1),

      h3("5.4.2  方向边界扫描"),
      ...codeBlock([
        "def scan_direction_boundary(Zset_2nd, I_fixed, phi_start=-180, phi_end=180,",
        "                             phi_step=5, char_type='mho'):",
        "    \"\"\"",
        "    在 [-180, +180] 度范围内扫描，找到保护从动作变不动作的临界角度",
        "    返回：每个角度对应的注入量和动作状态",
        "    \"\"\"",
        "    results = []",
        "    phi = phi_start",
        "    while phi <= phi_end:",
        "        pt = calc_direction_boundary_inject(Zset_2nd, I_fixed, phi)",
        "        if char_type == 'mho':",
        "            pt['in_zone'] = is_in_mho(pt['Zm'], Zset_2nd)",
        "        results.append(pt)",
        "        phi += phi_step",
        "",
        "    # 找临界角（动作→不动作的跳变）",
        "    boundaries = []",
        "    for i in range(len(results)-1):",
        "        if results[i]['in_zone'] != results[i+1]['in_zone']:",
        "            boundaries.append({",
        "                'phi_boundary': (results[i]['phi_deg'] + results[i+1]['phi_deg']) / 2,",
        "                'transition': 'operate→no_op' if results[i]['in_zone'] else 'no_op→operate'",
        "            })",
        "",
        "    # 对于标准 Mho，应有两个临界角：",
        "    #   forward_boundary  ≈ phi_set + 90°（正向边界）",
        "    #   backward_boundary ≈ phi_set - 90°（反向边界）",
        "    return {'scan': results, 'boundaries': boundaries}",
      ]),
      ...sp(1),

      h3("5.4.3  正反向边界精确计算"),
      ...codeBlock([
        "def calc_exact_direction_boundaries(Zset_2nd, char_type='mho'):",
        "    \"\"\"",
        "    精确计算 Mho 圆特性的正向和反向临界角",
        "",
        "    Mho 圆以 Zset/2 为圆心，|Zset|/2 为半径",
        "    当 Zm = r × exp(j×phi) 在圆上时：",
        "       |r×exp(j×phi) - Zset/2|² = (|Zset|/2)²",
        "",
        "    对于固定模长 |Zm| = r，令 phi 变化，",
        "    在 phi 为以下两值时 Zm 恰好在圆上：",
        "       phi = phi_set ± 90°",
        "    （这是当 |Zm| 趋近于 |Zset| 时的极限情况）",
        "",
        "    实用结论（标准 Mho 圆）：",
        "       正向动作边界角 = phi_set + 90°（含修正项）",
        "       反向死区边界角 = phi_set - 90°（含修正项）",
        "    \"\"\"",
        "    phi_set = math.degrees(cmath.phase(Zset_2nd))",
        "",
        "    forward_limit  = phi_set + 90.0   # 正向临界",
        "    backward_limit = phi_set - 90.0   # 反向临界（= -180+phi_set+90）",
        "",
        "    return {",
        "        'phi_set_deg':      phi_set,",
        "        'forward_limit_deg': forward_limit,   # Zm 相角超过此值则出圆",
        "        'backward_limit_deg': backward_limit, # Zm 相角小于此值则出圆",
        "        'operate_range_deg': (backward_limit, forward_limit),",
        "        'note': '仅适用于标准 Mho 圆，偏移圆需修正圆心坐标后重算'",
        "    }",
      ]),
      ...sp(2),
      new Paragraph({ children: [new PageBreak()] }),

      // ═══════════════════ 第六章 ═══════════════════
      h1("第六章  继保测试仪接线方案与加量方式"),

      h2("6.1  标准接线拓扑"),
      para("距离保护校验标准接线：三路电压（UA、UB、UC）+ 三路电流（IA、IB、IC）+ 开入量采集跳闸时间。"),
      ...sp(1),
      new Table({
        width: { size: 9500, type: WidthType.DXA },
        columnWidths: [2000, 2200, 2000, 3300],
        rows: [
          hRow(["测试仪通道", "接至保护端子", "信号类型", "说明"], [2000, 2200, 2000, 3300]),
          dRow(["U1（VA）", "保护 UA 输入", "电压", "A相相电压，参考相量"], [2000, 2200, 2000, 3300]),
          dRow(["U2（VB）", "保护 UB 输入", "电压", "B相相电压"], [2000, 2200, 2000, 3300], C.skyBlue),
          dRow(["U3（VC）", "保护 UC 输入", "电压", "C相相电压"], [2000, 2200, 2000, 3300]),
          dRow(["I1（IA）", "保护 IA 输入", "电流", "A相电流，注意极性方向"], [2000, 2200, 2000, 3300], C.skyBlue),
          dRow(["I2（IB）", "保护 IB 输入", "电流", "B相电流"], [2000, 2200, 2000, 3300]),
          dRow(["I3（IC）", "保护 IC 输入", "电流", "C相电流"], [2000, 2200, 2000, 3300], C.skyBlue),
          dRow(["DI1（开入）", "保护跳闸出口接点", "开关量", "测量动作时间（接在继电器常开触点）"], [2000, 2200, 2000, 3300]),
          dRow(["DI2（开入）", "TV 断线告警输出", "开关量", "可选，监视TV断线逻辑"], [2000, 2200, 2000, 3300], C.skyBlue),
        ]
      }),
      ...sp(1),
      noteBox("极性", "电流正方向：从母线流向线路（保护动作方向）。测试仪电流端正极→保护CT二次正极（P1/S1侧），负极→保护CT二次负极（S2侧），不得接反，否则保护看到反向故障不动作。", C.orange),
      ...sp(1),

      h2("6.2  相间故障加量方式"),
      h3("6.2.1  AB 相间短路（最典型）"),
      ...codeBlock([
        "  以 AB 相间故障、定电流 5A 为例：",
        "",
        "  测量回路：U_AB = U_A - U_B，I_loop = I_A - I_B",
        "",
        "  ┌─────────────────────────────────────────────────┐",
        "  │  通道   │  幅值        │  相角         │  说明  │",
        "  ├─────────────────────────────────────────────────┤",
        "  │  U_A    │  |Zm|×5/√3  │  φ_U + 30°    │ 相电压 │",
        "  │  U_B    │  |Zm|×5/√3  │  φ_U + 30° - 120° │    │",
        "  │  U_C    │  Un/√3/nPT  │  φ_U + 30° + 120° │ 正常│",
        "  │  I_A    │  5.000 A    │  0.00°        │ 参考   │",
        "  │  I_B    │  5.000 A    │  180.00°      │ 反向   │",
        "  │  I_C    │  0.000 A    │  0.00°        │ 不参与 │",
        "  └─────────────────────────────────────────────────┘",
        "",
        "  其中 φ_U = 电压超前电流角度 = 阻抗角 = angle(Zm_target)",
        "  （通常等于线路灵敏角，如 70°）",
        "",
        "  注：U_A 的相角参考 I_A（0°），",
        "      U_A 超前 I_A  φ_U 度，即 angle(U_A) = φ_U（相对 I_A）",
      ]),
      ...sp(1),

      h3("6.2.2  BC / CA 相间故障"),
      ...codeBlock([
        "  BC 相间：整体旋转 -120°",
        "    I_B = 5A @ 0°,  I_C = 5A @ 180°,  I_A = 0A",
        "    U_B, U_C 按旋转后的线电压计算，U_A 保持正常",
        "",
        "  CA 相间：整体旋转 +120°",
        "    I_C = 5A @ 0°,  I_A = 5A @ 180°,  I_B = 0A",
        "    U_C, U_A 按旋转后计算，U_B 保持正常",
      ]),
      ...sp(1),

      h2("6.3  接地故障加量方式（含零序补偿）"),
      ...codeBlock([
        "  A 相接地故障、定电流 I_A = 5A @ 0° 为例：",
        "",
        "  测量电流（保护内部）：",
        "    I_measure = I_A + K0 × (I_A + I_B + I_C)",
        "    → 需要计算 I_B, I_C 的零序分量",
        "",
        "  对于纯单相接地（无其他相电流时的理想注入）：",
        "    若直接只注入 I_A = 5A，则 I_0 = I_A/3",
        "    保护测量电流 = I_A × (1 + K0)",
        "    等效测量阻抗 = U_A / (I_A × (1+K0))",
        "",
        "  ┌───────────────────────────────────────────────────┐",
        "  │ 通道  │  幅值              │  相角   │  说明       │",
        "  ├───────────────────────────────────────────────────┤",
        "  │ U_A   │ |Zm|×|I_measure|  │  φ_U    │ 故障相电压  │",
        "  │ U_B   │ Un/√3/nPT         │ -120°   │ 正常相      │",
        "  │ U_C   │ Un/√3/nPT         │ +120°   │ 正常相      │",
        "  │ I_A   │ 5.000 A           │  0.00°  │ 故障相      │",
        "  │ I_B   │ 0.000 A           │  0.00°  │ 简化模式    │",
        "  │ I_C   │ 0.000 A           │  0.00°  │ 简化模式    │",
        "  └───────────────────────────────────────────────────┘",
        "",
        "  【重要】等效测量阻抗需用 I_measure = I_A×(1+K0) 计算：",
        "    Zm = U_A / I_measure = U_A / (I_A × (1 + K0))",
        "    因此：U_A = Zm_target × I_A × (1 + K0)",
      ]),
      ...sp(1),
      noteBox("注意", "单独只注入 I_A 时，保护看到的零序电流 3I0=I_A（不是3倍），请确认保护装置的零序补偿接入方式（有些用独立的 3I0 端子，有些从 IA+IB+IC 内部求和）。", C.red),
      ...sp(1),

      h2("6.4  方向边界校验加量方式"),
      h3("6.4.1  固定电流幅值，改变电压相角"),
      ...codeBlock([
        "  标准做法：固定 I_A = 5A @ 0°，从 phi = -180° 扫到 +180°",
        "  每步改变 U_AB 的相角（即改变电压超前电流的角度）",
        "",
        "  对应 AB 相间故障方向扫描：",
        "    I_A = 5A @ 0°,  I_B = 5A @ 180°  （固定不变）",
        "    U_A = ? @ phi°  （每步改变相角，幅值固定为某个值）",
        "    U_B = U_A @ (phi - 120°)           （保持三相对称关系）",
        "",
        "  每步判断：is_in_mho(U_AB / (I_A - I_B), Zset_II)",
        "  记录动作/不动作状态，找到跳变点即为方向边界",
        "",
        "  正向动作区（典型 Mho 70° 整定）：",
        "    phi 约在 -20° ~ 160° 之间（即 70°-90° ~ 70°+90°）",
        "    phi < -20°：反向不动作区",
        "    phi > 160°：正向过灵敏边界（实际不会超过 170°）",
      ]),
      ...sp(1),

      h3("6.4.2  反向死区验证"),
      ...codeBlock([
        "  反向死区：当 phi = phi_set - 90° ≈ 70°-90° = -20° 附近",
        "  此时出线侧故障保护不应动作",
        "",
        "  验证方法：",
        "    注入 I_A = 额定电流 × 5  （大电流，确保超过门槛）",
        "    U_AB 幅值保持正常（如 57.7V）",
        "    令 phi = -30°（反向）：保护应不动作 ✓",
        "    令 phi = +10°（正向边界内）：保护应动作  ✓",
        "",
        "  偏移圆特性（有反向延伸时）：",
        "    反向保护范围 = 整定值 × 偏移量（如 0.1×Zset）",
        "    phi 在 phi_set-90° 到 phi_set-90°-偏移弧度 之间仍动作",
      ]),
      ...sp(2),
      new Paragraph({ children: [new PageBreak()] }),

      // ═══════════════════ 第七章 ═══════════════════
      h1("第七章  完整主函数与输出数据结构"),

      h2("7.1  主函数入口"),
      ...codeBlock([
        "def calc_distance_protection_test(",
        "    # ── 系统参数（一次侧）──",
        "    Un_kV,              # float: 额定线电压 kV",
        "    nCT,                # float: CT变比（如 120.0 for 600/5）",
        "    nPT,                # float: PT变比（如 1100.0 for 110kV/100V）",
        "    Z1_per_km,          # tuple: (R1, X1) Ω/km 正序",
        "    Z0_per_km,          # tuple: (R0, X0) Ω/km 零序",
        "    Zs,                 # tuple: (Rs, Xs) Ω 系统背后阻抗",
        "    L_km,               # float: 线路全长",
        "    # ── 保护整定参数（二次侧）──",
        "    Zset_I,             # complex: I 段整定阻抗（二次Ω）",
        "    Zset_II,            # complex: II 段",
        "    Zset_III,           # complex: III 段",
        "    t_I, t_II, t_III,   # float: 各段动作时间(s)",
        "    char_type,          # str: 'mho' | 'quad'",
        "    phi_set_deg,        # float: 线路灵敏角（度）",
        "    # ── 测试工况 ──",
        "    fault_type,         # str: 'AB'|'BC'|'CA'|'AG'|'BG'|'CG'|'ABC'",
        "    calc_mode,          # str: 'fixed_U' | 'fixed_I'",
        "    fixed_val,          # float: 定电压(V二次) 或 定电流(A二次)",
        "    Zm_target_2nd,      # complex: 目标测量阻抗（二次Ω）",
        "    test_purpose,       # str: 'operate'|'boundary'|'no_op'|'direction_scan'",
        "    zone=1,             # int: 1/2/3 目标校验段",
        "    Rf_primary=0.0,     # float: 过渡电阻（一次Ω）",
        "    d_km=None,          # float: 故障距离（填此项则自动计算Zm）",
        ") -> dict:",
        "",
        "    K0 = calc_K0(Z1_per_km, Z0_per_km)",
        "",
        "    # 若给定故障距离，自动计算目标阻抗",
        "    if d_km is not None:",
        "        Z1 = complex(Z1_per_km[0], Z1_per_km[1])",
        "        Zm_1st  = Z1 * d_km + Rf_primary",
        "        Zm_target_2nd = convert_to_secondary(Zm_1st, nCT, nPT)",
        "",
        "    # 选择计算模式",
        "    if calc_mode == 'fixed_U':",
        "        inject = calc_fixed_voltage(Zm_target_2nd, fixed_val, fault_type, phi_set_deg)",
        "    else:",
        "        inject = calc_fixed_current(Zm_target_2nd, fixed_val, fault_type)",
        "",
        "    # 段别判断",
        "    zone_result = judge_zone(Zm_target_2nd, Zset_I, Zset_II, Zset_III,",
        "                             char_type, t_I, t_II, t_III)",
        "",
        "    # 方向边界扫描（仅当 test_purpose='direction_scan' 时执行）",
        "    direction_scan = None",
        "    if test_purpose == 'direction_scan':",
        "        direction_scan = scan_direction_boundary(",
        "            Zset_II if zone == 2 else Zset_I,",
        "            fixed_val, phi_start=-180, phi_end=180, phi_step=5)",
        "",
        "    return {",
        "        # ── 基础信息 ──",
        "        'fault_type':     fault_type,",
        "        'calc_mode':      calc_mode,",
        "        'K0':             K0,",
        "        'Zm_target_2nd':  Zm_target_2nd,",
        "        'Zm_magnitude':   abs(Zm_target_2nd),",
        "        'Zm_angle_deg':   angle_deg(Zm_target_2nd),",
        "",
        "        # ── 测试仪注入量 ──",
        "        'inject_I': inject['inject_I'],   # I_A/I_B/I_C 各相幅值和相角",
        "        'inject_U': inject['inject_U'],   # U_A/U_B/U_C 各相幅值和相角",
        "",
        "        # ── 段别判断结果 ──",
        "        'zone_result':    zone_result,",
        "        'expected_action': zone_result['in_zone'],",
        "        'action_time_s':  zone_result['t_action'],",
        "",
        "        # ── 方向边界（可选）──",
        "        'direction_scan': direction_scan,",
        "        'direction_boundaries': direction_scan['boundaries'] if direction_scan else None,",
        "",
        "        # ── 接线指导 ──",
        "        'wiring_guide': {",
        "            'U_channel': 'UA/UB/UC → 保护UA/UB/UC相电压端子',",
        "            'I_channel': 'IA/IB/IC → 保护IA/IB/IC端子（正极朝母线方向）',",
        "            'DI_channel': '跳闸出口 → 测试仪开入1，测量动作时间',",
        "            'polarity_note': '电流正方向为从母线流向线路，接反则保护看反向故障',",
        "            'ground_note': '各路电流、电压的负极就近单点接地，不共地',",
        "        }",
        "    }",
      ]),
      ...sp(2),
      new Paragraph({ children: [new PageBreak()] }),

      // ═══════════════════ 第八章 ═══════════════════
      h1("第八章  测试项目清单与合格判据"),

      h2("8.1  标准测试项目"),
      new Table({
        width: { size: 9500, type: WidthType.DXA },
        columnWidths: [2100, 1500, 1800, 1800, 2300],
        rows: [
          hRow(["测试项目", "故障类型", "calc_mode", "test_purpose", "合格判据"], [2100, 1500, 1800, 1800, 2300]),
          dRow(["I 段定值校验", "AB/BC/CA", "fixed_I", "operate", "90%整定动作，110%不动（边界精度±5%）"], [2100, 1500, 1800, 1800, 2300]),
          dRow(["II 段定值校验", "AB/BC/CA", "fixed_I", "operate", "同 I 段，时间误差 ≤ 50ms"], [2100, 1500, 1800, 1800, 2300], C.skyBlue),
          dRow(["III 段定值校验", "AB/BC/CA", "fixed_I", "operate", "同 I 段，时间误差 ≤ 100ms"], [2100, 1500, 1800, 1800, 2300]),
          dRow(["接地距离校验", "AG/BG/CG", "fixed_I", "operate", "考虑 K0 修正后阻抗误差 ≤ 5%"], [2100, 1500, 1800, 1800, 2300], C.skyBlue),
          dRow(["方向边界校验", "AB", "fixed_I", "direction_scan", "正向90°-270°动作，反向不动"], [2100, 1500, 1800, 1800, 2300]),
          dRow(["三相短路校验", "ABC", "fixed_U", "operate", "各段阻抗误差 ≤ 5%"], [2100, 1500, 1800, 1800, 2300], C.skyBlue),
          dRow(["TV 断线闭锁", "AB", "fixed_I", "no_op", "TV断线后距离保护闭锁，不误动"], [2100, 1500, 1800, 1800, 2300]),
          dRow(["动作时间校验", "AB（I段）", "fixed_I", "operate", "大故障电流，测跳闸时间 ≤ 30ms"], [2100, 1500, 1800, 1800, 2300], C.skyBlue),
        ]
      }),
      ...sp(1),

      h2("8.2  常见问题排查"),
      new Table({
        width: { size: 9500, type: WidthType.DXA },
        columnWidths: [2800, 3200, 3500],
        rows: [
          hRow(["现象", "可能原因", "排查方法"], [2800, 3200, 3500]),
          dRow(["动作阻抗偏小（提前动作）", "CT/PT变比输入错误", "重算 nCT/nPT，验证二次额定电压/电流"], [2800, 3200, 3500]),
          dRow(["方向校验不通过（反向动作）", "电流极性接反", "对调IA端子的S1/S2，或反转测试仪电流方向"], [2800, 3200, 3500], C.skyBlue),
          dRow(["接地故障阻抗误差大", "K0系数未正确配置", "确认保护装置K0设置，与计算值比对"], [2800, 3200, 3500]),
          dRow(["时间不准（偏长/偏短）", "开入量接线错误或防抖延时", "检查DI接至常开触点，确认防抖时间设置"], [2800, 3200, 3500], C.skyBlue),
          dRow(["定电压模式电流过大/小", "Zm_target取值超出仪器范围", "改用定电流模式，或调整 Zm_target 点位"], [2800, 3200, 3500]),
          dRow(["Mho圆无法扫到边界", "phi_step 太大，跳过了临界点", "减小步长到 1° ~ 2°，用二分法精确查找"], [2800, 3200, 3500], C.skyBlue),
        ]
      }),
      ...sp(1),

      h2("8.3  AI 集成开发注意事项"),
      num([bold("测量阻抗定义区分："), txt("相间故障 Zm = U_φφ / (Iφ - Iφ)；接地故障 Zm = Uφ / (Iφ + K0 × 3I0)。两者不可混用。")]),
      num([bold("PT变比的相电压换算："), txt("Un/√3 为相电压（线电压除以√3），测试仪通常加相电压，不加线电压。")]),
      num([bold("阻抗角与电压超前电流角一致："), txt("angle(Zm) = angle(U_fault) - angle(I_loop)。测试仪电压相角 = 0° + Zm的相角（以电流为参考）。")]),
      num([bold("两种模式的等价性验证："), txt("calc_fixed_voltage 和 calc_fixed_current 在相同 Zm_target 下，应输出相同的 angle(U/I)，幅值按固定量缩放。")]),
      num([bold("非故障相电压处理："), txt("相间短路时非故障相保持额定电压（Un/√3/nPT），方向边界扫描时需保持该值不变，仅改变故障相的相角。")]),
      num([bold("三相对称短路特殊性："), txt("ABC 故障无零序，K0 不参与，但要注意测试仪加量时三相电流需严格对称。")]),
      num([bold("d_km 与 Zm_target 互斥："), txt("若给出故障距离 d_km，由算法自动折算 Zm；若直接给 Zm_target，则 d_km 可为 None。")]),
      ...sp(2),
      div(),
      new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { before: 180, after: 80 },
        children: [new TextRun({ text: "文档结束 | 线路距离保护校验核心算法手册 v1.0", font: "Arial", size: 18, color: C.midGray, italics: true })],
      }),
    ]
  }]
});

Packer.toBuffer(doc).then(b => {
  fs.writeFileSync("/mnt/user-data/outputs/线路距离保护校验算法手册.docx", b);
  console.log("Done");
});
